### PR TITLE
allow html in claim and use htmlname in layout

### PR DESCRIPTION
**Pull request by butonic**
add example for html in claim

merge after https://github.com/owncloud/core/pull/30882 has been merged

Signed-off-by: Jörn Friedrich Dreyer <jfd@butonic.de>

### CODE REVIEW

**Comment by mmattel** [comment]
Any update on this? master and stable10 are merged...

**Comment by DeepDiver1975** [comment]
no reviewer - no project - no lable - PRs like that are getting lost :man_shrugging: 

@butonic as usual: please take care of you open PRs ;-)

**Comment by butonic** [comment]
part of fixing for https://github.com/owncloud/core/issues/30881

documents how to use html in the claim.

- could be reviewed by @ChrisEdS, @karakayasemi or @settermjd  but none of them is available in the reviewers list :man_shrugging: 
- labels are not in sync with core ... adding enhancement ind good first issue
- No idea which project to assign this to ...

**Comment by DeepDiver1975** [comment]
>     * No idea which project to assign this to ...

always "current server *" so the mgmt part of the teams get in on their screen

**Comment by DeepDiver1975** [comment]
>     * could be reviewed by @ChrisEdS, @karakayasemi or @settermjd  but none of them is available in the reviewers list man_shrugging

repo is wrongly setup - fixed now - please fix such situations yourself or let others know - THX

**Review by karakayasemi — COMMENTED** [review]
The core change released with 10.2.0 I guess. We need to increase min-max version: https://github.com/owncloud/theme-example/blob/master/appinfo/info.xml#L13

**Comment by micbar** [comment]
@karakayasemi yes, commit welcome :-)

**Review by karakayasemi — APPROVED** [review]

**Pull request merged**
